create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  product_hunt_id bigint not null,
  slug text not null,
  name text not null,
  tagline text,
  description text,
  website_url text,
  product_hunt_url text not null,
  thumbnail_url text,
  launch_date date not null,
  launched_at timestamptz,
  featured_at timestamptz,
  daily_rank integer not null check (daily_rank > 0),
  votes_count integer not null default 0 check (votes_count >= 0),
  comments_count integer not null default 0 check (comments_count >= 0),
  topic_slugs text[] not null default '{}',
  topic_names text[] not null default '{}',
  screenshot_bucket text not null default 'screenshots' check (screenshot_bucket = 'screenshots'),
  screenshot_path text,
  screenshot_url text,
  screenshot_width integer check (screenshot_width > 0),
  screenshot_height integer check (screenshot_height > 0),
  screenshot_bytes integer check (screenshot_bytes >= 0),
  screenshot_mime_type text,
  screenshot_captured_at timestamptz,
  source_payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  constraint products_product_hunt_id_key unique (product_hunt_id),
  constraint products_launch_date_daily_rank_key unique (launch_date, daily_rank)
);

create index if not exists products_launch_date_rank_idx
  on public.products (launch_date desc, daily_rank asc);

create index if not exists products_launch_date_votes_idx
  on public.products (launch_date desc, votes_count desc, daily_rank asc);

create index if not exists products_topic_slugs_gin_idx
  on public.products using gin (topic_slugs);

create index if not exists products_slug_idx
  on public.products (slug);

create index if not exists products_screenshot_path_idx
  on public.products (screenshot_path)
  where screenshot_path is not null;

drop trigger if exists products_set_updated_at on public.products;

create trigger products_set_updated_at
before update on public.products
for each row
execute function public.set_updated_at();

alter table public.products enable row level security;

drop policy if exists "Public read access for products" on public.products;

create policy "Public read access for products"
on public.products
for select
to public
using (true);

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'screenshots',
  'screenshots',
  true,
  5242880,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do update
set
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;
